FUNCTION PBMAIN() AS LONG
    FUNCTION = 0
END FUNCTION

FUNCTION ISINFINITE(BYVAL v AS DOUBLE) AS LONG
    IF v <> 0 AND v * 2 = v THEN
        FUNCTION = -1
    ELSE
        FUNCTION = 0
    END IF
END FUNCTION
