#COMPILE EXE
' batch18_test.bas - #-metastatement directives (29 audited in batch 18)
' Exercises conditional compilation, stack size, alignment and debug options.
#COMPILE EXE
#DIM ALL
#OPTION EXPLICIT
#LINK "kernel32.lib"
#STACK 1048576
#ALIGN 4
#BLOAT NONE
#BREAK ON
#COM ON
#DEBUG BOUNDS ON
#DEBUG CODE ON
#DEBUG DISPLAY ON
#DEBUG ERROR ON
#DEBUG NUMERIC ON
#DEBUG PRINT ON
#EXPORT
#MESSAGES OFF
#OPTIMIZE SPEED
#PAGE
#PBFORMS
#REGISTER NONE
#RESOURCE "x.rc"
#TOOLS OFF
#UNIQUE ON
#UTILITY "x"
#IF %DEF(%PB_WIN10)
    #CONSOLE OFF
#ELSEIF %DEF(%PB_CC)
    #CONSOLE ON
#ELSE
    #CONSOLE ON
#ENDIF
#INCLUDE "win32api.inc"
FUNCTION PBMAIN() AS LONG
    PRINT "META-ALL-ACCEPTED"
    FUNCTION = 0
END FUNCTION
