#CONSOLE OFF
#COMPILE EXE

GLOBAL g_hDlg AS QUAD
GLOBAL g_hBtn AS QUAD

FUNCTION PBMAIN() AS LONG
    DIALOG NEW 0, "Test", 100, 100, 300, 200 TO g_hDlg
    CONTROL ADD BUTTON, g_hDlg, 100, "OK", 100, 60, 80, 30 TO g_hBtn
    MSGBOX "Dialog created"
END FUNCTION
