#CONSOLE OFF
#COMPILE EXE

GLOBAL g_hDlg AS QUAD

FUNCTION PBMAIN() AS LONG
    DIALOG NEW 0, "Batch 149: Dialog Before", 100, 100, 350, 250 TO g_hDlg
    DIALOG SET TEXT g_hDlg, "Dialog After"
    DIALOG SHOW MODAL g_hDlg CALL DlgProc
END FUNCTION

CALLBACK FUNCTION DlgProc()
    SELECT CASE CB.MSG
        CASE 2
            DIALOG END g_hDlg, 1
    END SELECT
END FUNCTION
