FUNCTION PBMAIN () AS LONG
    LOCAL h AS LONG
    LOCAL p AS QUAD
    GLOBALMEM ALLOC 64 TO h
    GLOBALMEM LOCK h TO p
    PRINT "handle = "; h
    PRINT "ptr = "; p
    GLOBALMEM FREE h TO 0
    FUNCTION = 0
END FUNCTION
